version: '3.8'

services:
  python-wrapper:
    container_name: python_wrapper

    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - .:/code/
      - ${PIP_CACHE_DIR:-cache-python-wrapper}:/root/.cache

volumes:
  cache-python-wrapper:
