AWSTemplateFormatVersion: 2010-09-09
Description: Create CloudFront
Metadata:

Parameters:

Mappings:

Conditions:

Resources:
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass:
        CacheBehaviors:
          -
        DefaultCacheBehavior:
        IPV6Enabled: true | false
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
      Tags:
        - Key: key
          Value: value

Outputs:
