AWSTemplateFormatVersion: 2010-09-09
Description: Create CloudFront
Metadata:

Parameters:

Mappings:

Conditions:

Resources:
  cloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass:
        CacheBehaviors:
          -
        DefaultCacheBehavior:
          TargetOriginId:
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 3600
          MaxTTL: 84600
          MinTTL: 60
          Compress: true
        IPV6Enabled: true | false
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: http-only
      Tags:
        - Key: key
          Value: value

Outputs:
